version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing" # run the `echo` command
      - run: npm install
      - run: CI=true npm run build
  
  test:
    docker: 
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing..." # run the `echo` command
      - run: npm test
  
  hithere:
    docker: 
      - image: circleci/node:8.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello from test" # run the `echo` command
  


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - hithere


